import { Poppins, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import SpeedDial from "@/components/ui/speed-dial.component";
import Header from "@/components/ui/header.component";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <Header />
        <SpeedDial />
        {children}
      </body>
    </html>
  );
}
